spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
